# pull official base image
FROM python:3.8.6-slim-buster

# set working directory
WORKDIR /usr/src/app

# copy requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# Updates packages and install git(required for coveralls)
RUN apt-get update
RUN apt-get -y install git

# Install mod-spatialite(required for geolocalization)
RUN apt-get -y install libsqlite3-mod-spatialite

# install dependencies
RUN pip install -r requirements.txt 

# copy app
COPY . /usr/src/app

# docker entrypoint for heroku
CMD ["sh", "./docker-entrypoint.dev.sh"]

