name: Continuous Integration and Delivery

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and up
        run: docker-compose up -d --build
      - name: run pytest
        run: docker exec bookbnb-postserver_web pytest --cov=postserver
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
  
    env:
      $HEROKU_APP_NAME: bookbnb-postserver

    steps:
      - uses: actions/checkout@v2
      - name: logins
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          echo ${HEROKU_PASSWORD} | docker login -u ${HEROKU_USERNAME} --password-stdin registry.heroku.com
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}

      - name: push container
        run: |
          docker build -t facutorraca/${HEROKU_APP_NAME} .
          docker tag facutorraca/${HEROKU_APP_NAME} registry.heroku.com/${HEROKU_APP_NAME}/web;
          docker push facutorraca/${HEROKU_APP_NAME};

      - name: release
        run: |
          heroku container:push web --app ${HEROKU_APP_NAME};
          heroku container:release web --app ${HEROKU_APP_NAME};

